# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src\\app.py'],
    pathex=['src'],
    binaries=[],
    datas=[('template', 'template')],
    hiddenimports=[
        "tkcalendar",
        "babel.numbers",
        "ui",
        "ui.app_core",
        "ui.mixin_documents",
        "ui.mixin_quote",
        "ui.mixin_label",
        "ui.mixin_schedule",
        "ui.mixin_trello",
        "ui.mixin_history",
        "ui.mixin_line",
        "core",
        "core.parser",
        "core.generator",
        "core.generator_fix",
        "core.generator_tag",
        "core.generator_label",
        "core.generator_inspection",
        "core.generator_schedule",
        "core.generator_quote",
        "core.generator_statement",
        "sync",
        "sync.syncer_trello",
        "sync.syncer_sheets",
        "sync.syncer_production",
        "sync.syncer_shipping_order",
        "sync.syncer_accounting",
        "sync.creator_trello",
        "sync.downloader_trello",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='QuoteFlow',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
